Disallow form submission with empty title
insightorchards/calendar-ui pull request #75
Opened 2022-12-21 05:20 UTC by elliedori

_Closes:_ #73 

## Summary of changes
This PR prevents submitting the event form without a title. If the user attempts to do so, they will see an error stating that the title cannot be empty,

## Dev notes

## Testing

- [x] Unit tests

#### Screenshot of UI (local testing in browser)

2022-12-23 22:28 UTC, Ashlynn223 commented on ui/src/EventForm.test.tsx
> +  });
We should use `toBeVisible` for checks that show something visually in the UI rather than `toBeInTheDocument`, if we can't figure out how to it may be worth adding a cypress test for the case. In this case I checked to see if `toBeInTheDocument` was working as intended with this test by adding a check before clicking the submit button and found that regardless of it being before or after the action `toBeInTheDocument` is always true and never false. This is because `toBeInTheDocument` will be true if it finds the element in the DOM regardless of it being rendered in the UI. When I plugged in `toBeVisible` it passes when expected.

Here's an excerpt from a stack overflow showing the difference between `toBeInTheDocument` and `toBeVisible`:
![image](https://user-images.githubusercontent.com/50315144/209410459-24fe434e-1987-4d5b-920f-ce467df8295a.png)

2022-12-23 22:29 UTC, Ashlynn223 requested changes
There's a tweak that can be made to the unit test, but it looks great and is ready to merge after it's fixed 🎉

2022-12-26 19:16 UTC, elliedori commented
@Ashlynn223 this is ready for re-review!

2022-12-26 19:40 UTC, Ashlynn223 approved these changes
Looks nice! Good to merge 💃

2022-12-26 19:40 UTC, merged